### ISSUE TITLE
反复重启，有问题吧

### ISSUE THREAD

**Issue by chenyuyou** [baiywt/R1PlusLTS-OpenWrt#1]

**Comment by unliar** [comment]
![image](https://user-images.githubusercontent.com/14177215/155869139-98335fbd-f56c-467f-949e-bb644d1468b6.png)

老是出现那个fixing recursive fault but reboot is needed! 

然后就是 dns 解析不了。

然后就得重启。

**Comment by baiywt** [comment]
你好，请问是做什么操作的时候出现这个问题？有具体的步骤可以复现吗？

**Comment by unliar** [comment]
> 你好，请问是做什么操作的时候出现这个问题？有具体的步骤可以复现吗？

我感觉可能是 我开了  openclash 才出现的问题，我关掉再观察观察
